default_platform(:android)

platform :android do
  desc "Deploy app on draft mode to the Play Store"
  lane :playstore do
    increment_android_version_code
  
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
  
    upload_to_play_store(
      track: 'internal',
      release_status: 'completed',
      skip_upload_apk: true,
      json_key: './fastlane/playstore-credentials.json'
    )
  end

  private_lane :increment_android_version_code do
    build_gradle_file = File.join(Dir.pwd, "../app/build.gradle")
  
    unless File.exist?(build_gradle_file)
      UI.user_error!("🚨 build.gradle file not found at: #{build_gradle_file}")
    end
  
    # Read the file
    gradle_contents = File.read(build_gradle_file)
  
    # Find the versionCode line and increment it
    new_gradle_contents = gradle_contents.gsub(/versionCode (\d+)/) do |match|
      current_version = match.split.last.to_i
      "versionCode #{current_version + 1}"
    end
  
    # Write the updated content back to the file
    File.write(build_gradle_file, new_gradle_contents)
  
    UI.success("✅ Android versionCode incremented successfully!")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

